const $=s=>document.querySelector(s),grid=$("#channelGrid"),search=$("#search"),resultCount=$("#resultCount"),countPill=$("#countPill"),video=$("#video"),empty=$("#playerEmpty"),loading=$("#loading"),statusText=$("#statusText"),statusDot=$("#statusDot"),nowTitle=$("#nowTitle");
let channels=[],filter="all",hls=null;const favorites=new Set(JSON.parse(localStorage.getItem("rajib-tv-favorites")||"[]"));
const norm=s=>String(s||"").toLowerCase().replace(/\(.*?\)|\[.*?\]/g,"").replace(/[^a-z0-9]+/g,"").replace(/hd$/g,"");
function category(n){n=n.toLowerCase();if(/cricket|sports|sport|bein|star sports|fifa|football|golf|tennis|nhl|n sports/.test(n))return"Sports";if(/news|cnn|bbc|ndtv|aaj tak|abp|zee news|somoy|ekattor|dbc|independent/.test(n))return"News";if(/movie|cinema|hbo|star gold|colors cineplex|sony max|hits|mnx|movies now/.test(n))return"Movies";if(/cartoon|kids|doraemon|tom|jerry|pogo|nick|sonic|disney|hungama/.test(n))return"Kids";if(/star jalsha|zee bangla|bangla|atn|ekushey|rtv|channel i|channel s|ntv|g tv|global tv|deshi|maasranga|deepto|duronto/.test(n))return"Bangla";return"Entertainment"}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function initials(n){return n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'TV'}
function render(){let q=search.value.trim().toLowerCase(),list=channels.filter(c=>(filter==='all'||category(c.name)===filter)&&(c.name+' '+c.display).toLowerCase().includes(q));if($("#favOnlyBtn").classList.contains('active'))list=list.filter(c=>favorites.has(c.url));resultCount.textContent=`${list.length} CHANNELS`;grid.innerHTML='';list.forEach((c,i)=>{let card=document.createElement('article');card.className='channel-card';card.style.animationDelay=Math.min(i*14,420)+'ms';let fav=favorites.has(c.url);card.innerHTML=`<button class="fav ${fav?'on':''}">${fav?'♥':'♡'}</button><div class="card-top">${c.logo?`<img class="logo" src="${esc(c.logo)}" alt="${esc(c.name)}" loading="lazy">`:`<div class="fallback-logo">${initials(c.name)}</div>`}</div><div class="card-bottom"><div class="card-name" title="${esc(c.name)}">${esc(c.name)}</div><div class="card-meta"><span>${category(c.name).toUpperCase()}</span><span>LIVE</span></div></div>`;let img=card.querySelector('img');if(img)img.onerror=()=>{img.outerHTML=`<div class="fallback-logo">${initials(c.name)}</div>`};card.querySelector('.fav').onclick=e=>{e.stopPropagation();favorites.has(c.url)?favorites.delete(c.url):favorites.add(c.url);localStorage.setItem('rajib-tv-favorites',JSON.stringify([...favorites]));render()};card.onclick=()=>play(c);grid.appendChild(card)})}
function status(t,ok=false){statusText.textContent=t;statusDot.style.background=ok?'#22d3ee':'#666';statusDot.style.boxShadow=ok?'0 0 12px #22d3ee':'none'}
function play(c){nowTitle.textContent=c.name;empty.style.display='none';video.style.display='block';loading.style.display='flex';status('CONNECTING…');if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');let u=c.url.split('#')[0];if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,maxBufferLength:30});hls.loadSource(u);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{loading.style.display='none';status('LIVE',true);video.play().catch(()=>{})});hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal){loading.style.display='none';status('STREAM ERROR')}})}else{video.src=u;video.onloadedmetadata=()=>{loading.style.display='none';status('LIVE',true);video.play().catch(()=>{})}}}
async function enrichWithRealLogos(list){try{let [a,b]=await Promise.all([fetch('https://iptv-org.github.io/api/channels.json'),fetch('https://iptv-org.github.io/api/logos.json')]);if(!a.ok||!b.ok)return list;let cs=await a.json(),ls=await b.json(),byName=new Map(),byId=new Map();for(let c of cs)for(let n of [c.name,...(c.alt_names||[])]){let k=norm(n);if(k&&!byName.has(k))byName.set(k,c.id)}for(let l of ls)if(l.channel&&l.url&&l.in_use!==false&&!byId.has(l.channel))byId.set(l.channel,l.url);let hits=0;for(let c of list){let id=byName.get(norm(c.name))||byName.get(norm(c.display)),logo=id&&byId.get(id);if(logo){c.logo=logo;hits++}}console.log('Rajib Tv Show logos matched:',hits)}catch(e){console.warn('Logo service unavailable',e)}return list}
search.addEventListener('input',render);$("#filters").onclick=e=>{let b=e.target.closest('.filter');if(!b)return;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()};$("#favOnlyBtn").onclick=()=>{$("#favOnlyBtn").classList.toggle('active');render()};$("#muteBtn").onclick=()=>{video.muted=!video.muted;$("#muteBtn").textContent=video.muted?'🔇':'🔊'};$("#fullBtn").onclick=()=>$("#videoStage").requestFullscreen?.();$("#themeBtn").onclick=()=>document.body.classList.toggle('brighter');
fetch('channels.json').then(r=>r.json()).then(async d=>{channels=await enrichWithRealLogos(d);countPill.textContent=`${channels.length} CHANNELS`;render()}).catch(()=>grid.innerHTML='<div style="color:#aaa;padding:30px">Could not load channel list.</div>');
